// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzrffvjywbzqpdwbdavu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6cmZmdmp5d2J6cXBkd2JkYXZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NjU1MDgsImV4cCI6MjA2NjA0MTUwOH0.5G7i6L_shwP-EPGHrM0NR7i-jVj-I1EHIPPTYJULAs0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);